#!/bin/bash

# Määrame kausta, kus käib töö
current_dir=$(pwd)

# Kontrollime, kas antud kaust on Git repoga kaust
if [ ! -d ".git" ]; then
    echo "See kaust ei ole Git repoga kaust. Palun initsialiseeri Git repo."
    exit 1
fi

# Kontrollige, kas git on installitud
if ! command -v git &> /dev/null; then
    echo "Git ei ole installitud."
    exit 1
fi

# Lisame kõik muudatused Git-i
git add .

# Kontrollime, kas on muudatusi, mida commit'ida
if git diff-index --quiet HEAD --; then
    echo "Pole muudatusi commit'imiseks."
    exit 0
fi

# Teeme commit'i
commitMessage="Automatiseeritud üleslaadimine skriptist $(basename "$current_dir")"
git commit -m "$commitMessage"

# Määrame remote repo URL-i
repoUrl="https://github.com/Adrian69420N/winpowershell_skriptimine.git"

git remote set-url origin "$repoUrl"

git push -u origin master

echo "Skript üles laetud GitHubi edukalt kaustast $current_dir"
